---
services
db:
  image: sandeep0712/flm.2026:dbimage
  ports:
    - "3306:3306"
  deploy:
    replicas: 1
auth_service:
  image: sandeep0712/flm.2026:authimage
  ports:
    - "5001:5001"
  deploy:
    replicas: 1
book_service:
  image: sandeep0712/flm.2026:bookimage
  ports:
    - "5002:5002"
  deploy:
    replicas: 1
borrow_service:
  image: sandeep0712/flm.2026:borrowimage
  ports:
    - "5003:5003"
  deploy:
    replicas: 1
app_service:
  image: sandeep0712/flm.2026:appimage
  ports:
    - "5000:5000"
  deploy:
    replicas: 1
